# Generated by Django 4.2.1 on 2023-06-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.TextField(default='Task to be completed', max_length=300),
        ),
    ]
