# Generated by Django 4.2.1 on 2023-06-14 04:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0003_todolist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='ListItem',
        ),
    ]
