# Generated by Django 4.2.1 on 2023-06-15 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0004_rename_todolist_listitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['priority', '-created']},
        ),
        migrations.RemoveField(
            model_name='list',
            name='item',
        ),
        migrations.AddField(
            model_name='list',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='list',
            name='priority',
            field=models.CharField(choices=[(1, 'High Priority'), (2, 'Medium Priority'), (3, 'Low Priority'), (4, 'Optional')], default=2, max_length=30),
        ),
        migrations.AddField(
            model_name='list',
            name='title',
            field=models.CharField(default='Item', max_length=30),
        ),
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ListItem',
        ),
    ]
