# Generated by Django 4.2.1 on 2023-06-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_alter_list_options_remove_list_item_list_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
