# Generated by Django 4.2.1 on 2023-06-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_list_created_alter_list_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='priority',
            field=models.CharField(choices=[(1, 'High Priority'), (2, 'Medium Priority'), (3, 'Low Priority'), (4, 'Optional')], default='Medium Priority', max_length=30),
        ),
    ]
