# Generated by Django 4.2.1 on 2023-06-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_alter_list_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='priority',
            field=models.CharField(choices=[('High Priority', 'High Priority'), ('Medium Priority', 'Medium Priority'), ('Low Priority', 'Low Priority'), ('Optional', 'Optional')], default='Medium Priority', max_length=30),
        ),
    ]
